import React, { useState } from 'react';
import {
  AuditReport,
  AuditCheck,
  CheckStatus,
  AiRecommendationResult,
} from '../../types/seo';
import { ScoreGauge } from '../common/ScoreGauge';
import { AdSlot } from '../common/AdSlot';
import { ShareReportModal } from './ShareReportModal';
import { AuditHistoryTracker } from './AuditHistoryTracker';
import { generateReportPdf } from '../../utils/pdfGenerator';
import {
  CheckCircle2,
  AlertTriangle,
  XCircle,
  Sparkles,
  Printer,
  Share2,
  Download,
  Copy,
  Check,
  ExternalLink,
  ChevronDown,
  ChevronUp,
  Shield,
  Layers,
  Zap,
  Smartphone,
  FileText,
  Link2,
  Code,
  ArrowRight,
  Gauge,
  Loader2,
  History,
} from 'lucide-react';

interface ReportViewProps {
  report: AuditReport;
  onRefresh?: () => void;
}

export const ReportView: React.FC<ReportViewProps> = ({ report, onRefresh }) => {
  const [activeTab, setActiveTab] = useState<string>('all');
  const [statusFilter, setStatusFilter] = useState<'ALL' | 'FAIL' | 'WARNING' | 'PASS'>('ALL');
  const [copiedLink, setCopiedLink] = useState(false);
  const [isGeneratingAi, setIsGeneratingAi] = useState(false);
  const [aiData, setAiData] = useState<AiRecommendationResult | undefined>(report.aiRecommendations);
  const [shareToken, setShareToken] = useState<string | null>(report.id || null);
  const [isShareModalOpen, setIsShareModalOpen] = useState(false);
  const [isGeneratingPdf, setIsGeneratingPdf] = useState(false);

  // Trigger Gemini AI recommendations if not already present
  const handleFetchAiRecommendations = async () => {
    if (aiData || isGeneratingAi) return;
    setIsGeneratingAi(true);
    try {
      const res = await fetch('/api/ai/advisor', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ report }),
      });
      if (res.ok) {
        const data = await res.json();
        setAiData(data);
      }
    } catch (err) {
      console.error('Failed to generate AI recommendations:', err);
    } finally {
      setIsGeneratingAi(false);
    }
  };

  // Save report and get shareable link
  const handleShareReport = async () => {
    try {
      if (!shareToken) {
        const res = await fetch('/api/reports/save', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ report }),
        });
        if (res.ok) {
          const data = await res.json();
          setShareToken(data.token);
          const shortUrl = `${window.location.origin}/r/${data.token}`;
          await navigator.clipboard.writeText(shortUrl);
        }
      } else {
        const shortUrl = `${window.location.origin}/r/${shareToken}`;
        await navigator.clipboard.writeText(shortUrl);
      }
      setCopiedLink(true);
      setIsShareModalOpen(true);
      setTimeout(() => setCopiedLink(false), 3000);
    } catch {
      setIsShareModalOpen(true);
    }
  };

  const handleDownloadPdf = async () => {
    try {
      setIsGeneratingPdf(true);
      await generateReportPdf(report);
    } catch (err) {
      console.error('Failed to generate PDF report:', err);
      // Fallback
      window.print();
    } finally {
      setIsGeneratingPdf(false);
    }
  };

  // Collect all checks
  const allChecks: AuditCheck[] = [
    ...report.categories.technical.checks,
    ...report.categories.onpage.checks,
    ...report.categories.performance.checks,
    ...report.categories.mobile.checks,
    ...report.categories.security.checks,
    ...report.categories.content.checks,
    ...report.categories.links.checks,
  ];

  const filteredChecks = allChecks.filter((c) => {
    if (activeTab !== 'all' && c.category !== activeTab) return false;
    if (statusFilter !== 'ALL' && c.status !== statusFilter) return false;
    return true;
  });

  return (
    <div className="space-y-8 animate-in fade-in duration-300">
      {/* Print-Only Header Branding */}
      <div className="hidden print:block border-b border-slate-300 pb-4 mb-6">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-bold text-slate-900">SEO Audit &amp; Diagnostic Report</h1>
            <p className="text-sm text-slate-600">Generated by SEOReportTools.com (Free Forever)</p>
          </div>
          <div className="text-right text-xs text-slate-500">
            <div>URL: {report.url}</div>
            <div>Date: {new Date(report.timestamp).toLocaleDateString()}</div>
          </div>
        </div>
      </div>

      {/* Top Action Toolbar (No-Print) */}
      <div className="print:hidden flex flex-wrap items-center justify-between gap-4 rounded-2xl bg-white p-4 sm:p-5 shadow-sm border border-slate-200">
        <div className="flex items-center gap-3">
          <div className="h-3 w-3 rounded-full bg-emerald-500 animate-pulse" />
          <div>
            <span className="text-xs text-slate-400 font-medium block">Audited URL</span>
            <a
              href={report.url}
              target="_blank"
              rel="noopener noreferrer"
              className="text-sm sm:text-base font-bold text-slate-900 hover:text-indigo-600 inline-flex items-center gap-1.5 truncate max-w-[280px] sm:max-w-md"
            >
              {report.url}
              <ExternalLink className="w-3.5 h-3.5 text-slate-400 shrink-0" />
            </a>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={handleShareReport}
            className="inline-flex items-center gap-1.5 rounded-xl border border-slate-200 bg-white px-3.5 py-2 text-xs font-semibold text-slate-700 shadow-sm hover:bg-slate-50 transition-colors"
          >
            {copiedLink ? <Check className="w-4 h-4 text-emerald-600" /> : <Share2 className="w-4 h-4 text-slate-500" />}
            <span>{copiedLink ? 'Link Copied!' : 'Share Report'}</span>
          </button>

          <button
            type="button"
            onClick={handleDownloadPdf}
            disabled={isGeneratingPdf}
            className="inline-flex items-center gap-1.5 rounded-xl bg-indigo-600 hover:bg-indigo-700 active:scale-98 px-4 py-2 text-xs font-bold text-white shadow-2xs transition-all cursor-pointer disabled:opacity-75"
            title="Download complete professional PDF report"
          >
            {isGeneratingPdf ? (
              <>
                <Loader2 className="w-4 h-4 animate-spin" />
                <span>Generating PDF...</span>
              </>
            ) : (
              <>
                <Download className="w-4 h-4" />
                <span>Download as PDF</span>
              </>
            )}
          </button>
        </div>
      </div>

      {/* Executive Score Summary Card */}
      <div className="rounded-3xl border border-slate-200/90 bg-white p-6 sm:p-8 shadow-sm">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-center">
          {/* Main Dial */}
          <div className="lg:col-span-4 flex flex-col items-center justify-center border-b lg:border-b-0 lg:border-r border-slate-100 pb-6 lg:pb-0 lg:pr-8">
            <ScoreGauge score={report.overallScore} size="lg" label="Overall SEO Health" />
            <p className="mt-3 text-center text-xs text-slate-500 max-w-[220px]">
              Calculated dynamically via 7 weighted diagnostic categories.
            </p>
          </div>

          {/* Issue Counters & Status */}
          <div className="lg:col-span-8 space-y-6">
            <div>
              <span className="text-xs font-bold uppercase tracking-wider text-indigo-600">
                Executive Diagnostic Summary
              </span>
              <h2 className="text-xl sm:text-2xl font-extrabold text-slate-900 tracking-tight mt-1">
                {report.overallScore >= 85
                  ? 'Strong SEO Foundation with Minor Optimizations'
                  : report.overallScore >= 65
                  ? 'Moderate SEO Health with Actionable Improvements'
                  : 'Critical Technical & Structural Issues Require Attention'}
              </h2>
              <p className="text-xs sm:text-sm text-slate-600 mt-2 leading-relaxed">
                Our automated crawler completed {report.statusSummary.totalChecks} specific technical checkpoints across {report.domain}. Below is the breakdown of passed checks, optimization warnings, and critical blockers.
              </p>
            </div>

            {/* Status Pills */}
            <div className="grid grid-cols-3 gap-3">
              <div className="flex flex-col rounded-2xl bg-emerald-50 border border-emerald-100 p-3 sm:p-4 text-center">
                <span className="text-2xl sm:text-3xl font-extrabold text-emerald-700">
                  {report.statusSummary.passCount}
                </span>
                <span className="text-[11px] sm:text-xs font-semibold text-emerald-800 mt-1 flex items-center justify-center gap-1">
                  <CheckCircle2 className="w-3.5 h-3.5" /> Passed
                </span>
              </div>

              <div className="flex flex-col rounded-2xl bg-amber-50 border border-amber-100 p-3 sm:p-4 text-center">
                <span className="text-2xl sm:text-3xl font-extrabold text-amber-700">
                  {report.statusSummary.warningCount}
                </span>
                <span className="text-[11px] sm:text-xs font-semibold text-amber-800 mt-1 flex items-center justify-center gap-1">
                  <AlertTriangle className="w-3.5 h-3.5" /> Warnings
                </span>
              </div>

              <div className="flex flex-col rounded-2xl bg-rose-50 border border-rose-100 p-3 sm:p-4 text-center">
                <span className="text-2xl sm:text-3xl font-extrabold text-rose-700">
                  {report.statusSummary.criticalCount}
                </span>
                <span className="text-[11px] sm:text-xs font-semibold text-rose-800 mt-1 flex items-center justify-center gap-1">
                  <XCircle className="w-3.5 h-3.5" /> Critical
                </span>
              </div>
            </div>

            {/* Quick Metrics Bar */}
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 pt-2 text-xs border-t border-slate-100 text-slate-500">
              <div>
                <span className="text-[10px] uppercase font-bold text-slate-400 block">Response Time</span>
                <span className="font-semibold text-slate-800">{report.technical.responseTimeMs} ms</span>
              </div>
              <div>
                <span className="text-[10px] uppercase font-bold text-slate-400 block">Document Weight</span>
                <span className="font-semibold text-slate-800">{report.technical.htmlSizeKb} KB</span>
              </div>
              <div>
                <span className="text-[10px] uppercase font-bold text-slate-400 block">Word Count</span>
                <span className="font-semibold text-slate-800">{report.content.wordCount} words</span>
              </div>
              <div>
                <span className="text-[10px] uppercase font-bold text-slate-400 block">HTTP Protocol</span>
                <span className="font-semibold text-slate-800">{report.technical.isHttps ? 'HTTPS (Secure)' : 'HTTP (Insecure)'}</span>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* AdSlot Between Header & Categories (No-Print) */}
      <div className="print:hidden">
        <AdSlot format="horizontal" />
      </div>

      {/* Official Google Lighthouse & Core Web Vitals Card */}
      {report.googlePageSpeed && (
        <div className="rounded-3xl border border-indigo-100 bg-gradient-to-br from-indigo-50/50 via-white to-violet-50/30 p-6 sm:p-7 shadow-xs space-y-5">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-indigo-100/70 pb-4">
            <div className="flex items-center gap-3">
              <div className="p-2.5 rounded-2xl bg-indigo-600 text-white shadow-sm">
                <Gauge className="w-5 h-5" />
              </div>
              <div>
                <div className="flex items-center gap-2">
                  <span className="text-[11px] font-extrabold uppercase tracking-wider text-indigo-700">
                    Official Google Lighthouse Diagnostics
                  </span>
                  <span className="px-2 py-0.5 rounded text-[10px] font-extrabold uppercase bg-emerald-100 text-emerald-800">
                    {report.googlePageSpeed.dataSource === 'google_official_api' ? 'Google API Verified' : 'Lighthouse Engine (95%+ Accurate)'}
                  </span>
                </div>
                <h3 className="text-lg font-bold text-slate-900">
                  Google Core Web Vitals &amp; Audit Scores
                </h3>
              </div>
            </div>
            <div className="text-left sm:text-right">
              <span className="text-xs text-slate-500 font-medium">Tested Strategy: Mobile</span>
            </div>
          </div>

          {/* 4 Google Lighthouse Category Badges */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
            {[
              { label: 'Google SEO', score: report.googlePageSpeed.lighthouseScores.seo },
              { label: 'Performance', score: report.googlePageSpeed.lighthouseScores.performance },
              { label: 'Accessibility', score: report.googlePageSpeed.lighthouseScores.accessibility },
              { label: 'Best Practices', score: report.googlePageSpeed.lighthouseScores.bestPractices },
            ].map((item, idx) => {
              const color =
                item.score >= 90 ? 'text-emerald-700 bg-emerald-50 border-emerald-200' :
                item.score >= 50 ? 'text-amber-700 bg-amber-50 border-amber-200' :
                'text-rose-700 bg-rose-50 border-rose-200';
              return (
                <div key={idx} className={`p-3.5 rounded-2xl border text-center space-y-1 ${color}`}>
                  <span className="text-[11px] font-bold uppercase text-slate-600 block">{item.label}</span>
                  <div className="text-2xl sm:text-3xl font-black">{item.score}</div>
                  <span className="text-[10px] text-slate-400">/ 100</span>
                </div>
              );
            })}
          </div>

          {/* Google Core Web Vitals Cards */}
          <div className="grid grid-cols-1 sm:grid-cols-3 lg:grid-cols-5 gap-3 pt-2">
            {[
              { label: 'LCP (Largest Paint)', item: report.googlePageSpeed.coreWebVitals.lcp, target: '&le; 2.5s' },
              { label: 'FCP (First Contentful)', item: report.googlePageSpeed.coreWebVitals.fcp, target: '&le; 1.8s' },
              { label: 'CLS (Layout Shift)', item: report.googlePageSpeed.coreWebVitals.cls, target: '&le; 0.1' },
              { label: 'TBT (Blocking Time)', item: report.googlePageSpeed.coreWebVitals.tbt, target: '&le; 200ms' },
              { label: 'Speed Index', item: report.googlePageSpeed.coreWebVitals.speedIndex, target: '&le; 3.4s' },
            ].map((vital, idx) => (
              <div key={idx} className="p-3.5 rounded-2xl border border-slate-200 bg-white shadow-2xs space-y-1">
                <div className="flex items-center justify-between">
                  <span className="text-[11px] font-bold text-slate-700 truncate">{vital.label}</span>
                  <span className={`px-1.5 py-0.5 rounded text-[9px] font-extrabold uppercase ${vital.item.status === 'good' ? 'bg-emerald-100 text-emerald-800' : 'bg-amber-100 text-amber-800'}`}>
                    {vital.item.status}
                  </span>
                </div>
                <div className="text-xl font-black text-slate-900">{vital.item.displayValue}</div>
                <span className="text-[10px] text-slate-400 block" dangerouslySetInnerHTML={{ __html: `Target: ${vital.target}` }} />
              </div>
            ))}
          </div>
        </div>
      )}

      {/* 7 Category Score Cards Grid */}
      <div>
        <div className="flex items-center justify-between mb-4">
          <h3 className="text-base sm:text-lg font-bold text-slate-900">
            Category Performance Breakdown
          </h3>
          <a
            href="/seo-score-methodology"
            className="text-xs font-semibold text-indigo-600 hover:text-indigo-700"
          >
            How are these weighted? →
          </a>
        </div>

        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-7 gap-3">
          {[
            { key: 'technical', label: 'Technical SEO', weight: '20%', icon: Layers, data: report.categories.technical },
            { key: 'onpage', label: 'On-Page SEO', weight: '20%', icon: Code, data: report.categories.onpage },
            { key: 'performance', label: 'Performance', weight: '20%', icon: Zap, data: report.categories.performance },
            { key: 'mobile', label: 'Mobile', weight: '10%', icon: Smartphone, data: report.categories.mobile },
            { key: 'security', label: 'Security', weight: '10%', icon: Shield, data: report.categories.security },
            { key: 'content', label: 'Content', weight: '10%', icon: FileText, data: report.categories.content },
            { key: 'links', label: 'Links', weight: '10%', icon: Link2, data: report.categories.links },
          ].map((cat) => (
            <button
              key={cat.key}
              type="button"
              onClick={() => setActiveTab(cat.key)}
              className={`flex flex-col items-center justify-between rounded-2xl p-4 text-center border transition-all ${
                activeTab === cat.key
                  ? 'border-indigo-600 bg-indigo-50/50 shadow-sm ring-1 ring-indigo-600'
                  : 'border-slate-200/90 bg-white hover:border-slate-300'
              }`}
            >
              <div className="flex items-center gap-1.5 text-slate-400">
                <cat.icon className="w-4 h-4 text-indigo-600" />
                <span className="text-[10px] font-bold uppercase">{cat.weight}</span>
              </div>
              <div className="my-2">
                <span className={`text-2xl font-black ${
                  cat.data.score >= 80 ? 'text-emerald-600' : cat.data.score >= 60 ? 'text-amber-600' : 'text-rose-600'
                }`}>
                  {cat.data.score}
                </span>
                <span className="text-[10px] text-slate-400 block font-semibold">/100</span>
              </div>
              <span className="text-xs font-bold text-slate-800 leading-tight">
                {cat.label}
              </span>
            </button>
          ))}
        </div>
      </div>

      {/* AI SEO Advisor Integration */}
      <div className="rounded-3xl border border-indigo-100 bg-gradient-to-br from-indigo-50/70 via-white to-violet-50/50 p-6 sm:p-8 shadow-sm">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-6 border-b border-indigo-100">
          <div className="flex items-center gap-3">
            <div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-indigo-600 text-white shadow-md shadow-indigo-500/20">
              <Sparkles className="h-6 w-6" />
            </div>
            <div>
              <span className="text-xs font-bold uppercase tracking-wider text-indigo-600">
                AI SEO Advisor
              </span>
              <h3 className="text-lg sm:text-xl font-extrabold text-slate-900 tracking-tight">
                Intelligent Action Plan &amp; Fixes
              </h3>
            </div>
          </div>

          {!aiData && (
            <button
              type="button"
              disabled={isGeneratingAi}
              onClick={handleFetchAiRecommendations}
              className="inline-flex items-center justify-center gap-2 rounded-xl bg-indigo-600 px-5 py-2.5 text-xs font-bold text-white shadow-sm hover:bg-indigo-700 transition-colors disabled:opacity-50"
            >
              <Sparkles className="w-4 h-4" />
              <span>{isGeneratingAi ? 'Analyzing with Gemini...' : 'Generate AI Action Plan'}</span>
            </button>
          )}
        </div>

        {aiData ? (
          <div className="mt-6 space-y-6">
            {/* AI Summary */}
            <div className="rounded-2xl bg-white p-5 border border-indigo-100/80 shadow-sm">
              <span className="text-xs font-bold uppercase tracking-wider text-slate-400 block mb-1">
                Strategic Diagnosis
              </span>
              <p className="text-sm font-medium text-slate-800 leading-relaxed">
                {aiData.summary}
              </p>
            </div>

            {/* Quick Wins */}
            {aiData.quick_wins?.length > 0 && (
              <div>
                <h4 className="text-xs font-bold uppercase tracking-wider text-slate-900 mb-3 flex items-center gap-1.5">
                  <Zap className="w-3.5 h-3.5 text-amber-500" />
                  <span>Immediate Quick Wins (Do These First)</span>
                </h4>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                  {aiData.quick_wins.map((win, idx) => (
                    <div key={idx} className="flex items-start gap-2.5 rounded-xl bg-white p-3.5 border border-slate-200 text-xs">
                      <span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-emerald-100 text-emerald-700 font-bold text-[10px]">
                        ✓
                      </span>
                      <span className="font-semibold text-slate-800">{win}</span>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Phased Action Plan */}
            {aiData.action_plan?.length > 0 && (
              <div>
                <h4 className="text-xs font-bold uppercase tracking-wider text-slate-900 mb-3">
                  30-Day Phased Implementation Roadmap
                </h4>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                  {aiData.action_plan.map((phase, pIdx) => (
                    <div key={pIdx} className="rounded-2xl bg-white p-4 border border-slate-200 shadow-sm space-y-2">
                      <div className="flex items-center justify-between">
                        <span className="text-xs font-bold text-indigo-600">{phase.phase}</span>
                        <span className="text-[10px] font-semibold px-2 py-0.5 rounded-full bg-slate-100 text-slate-600">
                          {phase.timeline}
                        </span>
                      </div>
                      <ul className="space-y-1.5 text-xs text-slate-600 pt-1">
                        {phase.tasks.map((task, tIdx) => (
                          <li key={tIdx} className="flex items-start gap-1.5">
                            <span className="text-indigo-500 font-bold">•</span>
                            <span>{task}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        ) : (
          <div className="mt-6 flex flex-col items-center justify-center py-6 text-center">
            <p className="text-xs text-slate-500 max-w-md">
              Click the button above to have Gemini synthesize your audit results into prioritized quick wins and a 30-day implementation plan.
            </p>
          </div>
        )}
      </div>

      {/* Interactive Checkpoints List & Filters */}
      <div className="rounded-3xl border border-slate-200/90 bg-white p-6 sm:p-8 shadow-sm">
        {/* Filter Bar */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-6 border-b border-slate-100">
          <div className="flex flex-wrap items-center gap-1.5">
            <button
              type="button"
              onClick={() => setActiveTab('all')}
              className={`rounded-lg px-3 py-1.5 text-xs font-bold transition-colors ${
                activeTab === 'all'
                  ? 'bg-indigo-600 text-white shadow-sm'
                  : 'bg-slate-100 text-slate-600 hover:bg-slate-200'
              }`}
            >
              All Categories ({allChecks.length})
            </button>
            {['technical', 'onpage', 'performance', 'mobile', 'security', 'content', 'links'].map((tab) => (
              <button
                key={tab}
                type="button"
                onClick={() => setActiveTab(tab)}
                className={`rounded-lg px-3 py-1.5 text-xs font-bold uppercase transition-colors ${
                  activeTab === tab
                    ? 'bg-indigo-600 text-white shadow-sm'
                    : 'bg-slate-100 text-slate-600 hover:bg-slate-200'
                }`}
              >
                {tab}
              </button>
            ))}
          </div>

          {/* Status Filter */}
          <div className="flex items-center gap-1.5">
            <span className="text-xs text-slate-400 font-medium">Status:</span>
            {(['ALL', 'FAIL', 'WARNING', 'PASS'] as const).map((filter) => (
              <button
                key={filter}
                type="button"
                onClick={() => setStatusFilter(filter)}
                className={`rounded-md px-2.5 py-1 text-[11px] font-bold transition-colors ${
                  statusFilter === filter
                    ? 'bg-slate-900 text-white'
                    : 'bg-slate-100 text-slate-600 hover:bg-slate-200'
                }`}
              >
                {filter === 'ALL' ? 'All' : filter === 'FAIL' ? 'Critical' : filter === 'WARNING' ? 'Warnings' : 'Passed'}
              </button>
            ))}
          </div>
        </div>

        {/* Checkpoints Items */}
        <div className="divide-y divide-slate-100 pt-2">
          {filteredChecks.length === 0 ? (
            <div className="py-12 text-center text-slate-400 text-xs">
              No checkpoints match the selected filters.
            </div>
          ) : (
            filteredChecks.map((check) => (
              <div key={check.id} className="py-4.5 space-y-2">
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
                  <div className="flex items-center gap-2.5">
                    {check.status === 'PASS' && <CheckCircle2 className="w-5 h-5 text-emerald-500 shrink-0" />}
                    {check.status === 'WARNING' && <AlertTriangle className="w-5 h-5 text-amber-500 shrink-0" />}
                    {check.status === 'FAIL' && <XCircle className="w-5 h-5 text-rose-500 shrink-0" />}
                    <div>
                      <h4 className="text-sm font-bold text-slate-900">{check.name}</h4>
                      <span className="text-[11px] font-semibold text-slate-400 uppercase tracking-wider">
                        {check.category} • Weight {check.weight}x
                      </span>
                    </div>
                  </div>

                  <div className="flex items-center gap-2">
                    {check.value !== undefined && (
                      <span className="text-xs font-mono bg-slate-100 text-slate-700 px-2 py-0.5 rounded truncate max-w-[200px] sm:max-w-xs">
                        {String(check.value)}
                      </span>
                    )}
                    <span
                      className={`px-2.5 py-0.5 rounded-full text-xs font-bold border ${
                        check.status === 'PASS'
                          ? 'bg-emerald-50 text-emerald-700 border-emerald-200'
                          : check.status === 'WARNING'
                          ? 'bg-amber-50 text-amber-700 border-amber-200'
                          : 'bg-rose-50 text-rose-700 border-rose-200'
                      }`}
                    >
                      {check.status}
                    </span>
                  </div>
                </div>

                <p className="text-xs text-slate-600 pl-7">{check.message}</p>

                {check.recommendation && (
                  <div className="ml-7 rounded-xl bg-slate-50 border border-slate-200/80 p-3 text-xs text-slate-700 space-y-1">
                    <span className="font-bold text-slate-900 flex items-center gap-1">
                      <Sparkles className="w-3.5 h-3.5 text-indigo-600" />
                      Recommended Action:
                    </span>
                    <p>{check.recommendation}</p>
                  </div>
                )}
              </div>
            ))
          )}
        </div>
      </div>

      {/* Historical Score Progression Chart (Local Storage + Recharts) */}
      <div className="print:hidden">
        <AuditHistoryTracker currentDomain={report.domain} />
      </div>

      {/* AdSlot Before Related Tools (No-Print) */}
      <div className="print:hidden">
        <AdSlot format="horizontal" />
      </div>

      {/* Deep Dives & Related Tools */}
      <div className="rounded-3xl border border-slate-200/90 bg-white p-6 sm:p-8 shadow-sm">
        <h3 className="text-base sm:text-lg font-bold text-slate-900 mb-1">
          Explore Specialized Free SEO Tools for This Site
        </h3>
        <p className="text-xs text-slate-500 mb-6">
          Investigate specific areas of your website with our 30+ dedicated single-purpose checkers.
        </p>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          {[
            { name: 'Meta Tag Analyzer', slug: 'meta-tag-analyzer', desc: 'Inspect title, description & SERP truncation.' },
            { name: 'Heading Analyzer', slug: 'heading-analyzer', desc: 'Examine complete H1, H2, and H3 hierarchies.' },
            { name: 'Robots.txt Checker', slug: 'robots-txt-checker', desc: 'Verify crawler accessibility & sitemap links.' },
            { name: 'Page Speed Checker', slug: 'page-speed-checker', desc: 'Audit server TTFB latency & compression.' },
          ].map((tool, idx) => (
            <a
              key={idx}
              href={`/tools/${tool.slug}`}
              className="flex flex-col justify-between rounded-2xl border border-slate-200 p-4 transition-all hover:border-indigo-600 hover:shadow-md group"
            >
              <div>
                <h4 className="text-sm font-bold text-slate-900 group-hover:text-indigo-600 transition-colors">
                  {tool.name}
                </h4>
                <p className="text-xs text-slate-500 mt-1">{tool.desc}</p>
              </div>
              <span className="text-xs font-bold text-indigo-600 mt-4 flex items-center gap-1">
                Open Tool <ArrowRight className="w-3.5 h-3.5" />
              </span>
            </a>
          ))}
        </div>
      </div>

      {shareToken && (
        <ShareReportModal
          isOpen={isShareModalOpen}
          onClose={() => setIsShareModalOpen(false)}
          report={report}
          token={shareToken}
        />
      )}
    </div>
  );
};
