import jsPDF from 'jspdf';
import { AuditReport } from '../types/seo';

/**
 * Generates a professional, branded SEO Audit Report PDF document
 */
export async function generateReportPdf(report: AuditReport): Promise<void> {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 14;
  const contentWidth = pageWidth - margin * 2;

  let currentY = margin;

  // Helper: Draw Header on pages
  const drawHeader = (pageNumber: number, totalPages: number) => {
    // Top accent bar
    doc.setFillColor(79, 70, 229); // Indigo 600
    doc.rect(0, 0, pageWidth, 4, 'F');

    // Mini Brand Header
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139);
    doc.text('SEO REPORT TOOLS', margin, 10);

    doc.setFont('helvetica', 'normal');
    doc.text(`Domain: ${report.domain}`, pageWidth / 2, 10, { align: 'center' });
    doc.text(`Page ${pageNumber} of ${totalPages}`, pageWidth - margin, 10, { align: 'right' });

    // Thin separator
    doc.setDrawColor(226, 232, 240);
    doc.setLineWidth(0.3);
    doc.line(margin, 13, pageWidth - margin, 13);
  };

  // Helper: Draw Footer on pages
  const drawFooter = () => {
    doc.setDrawColor(226, 232, 240);
    doc.setLineWidth(0.3);
    doc.line(margin, pageHeight - 12, pageWidth - margin, pageHeight - 12);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text('Generated by SEO Report Tools • https://seoreporttools.com', margin, pageHeight - 7);
    const dateStr = new Date(report.timestamp || Date.now()).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    });
    doc.text(`Audit Date: ${dateStr}`, pageWidth - margin, pageHeight - 7, { align: 'right' });
  };

  // Check and add page if needed
  const checkPageBreak = (neededHeight: number): boolean => {
    if (currentY + neededHeight > pageHeight - 18) {
      doc.addPage();
      currentY = 18;
      return true;
    }
    return false;
  };

  // ================= PAGE 1: COVER & EXECUTIVE SUMMARY =================

  // Top decorative hero block
  doc.setFillColor(15, 23, 42); // Slate 900
  doc.roundedRect(margin, currentY, contentWidth, 54, 4, 4, 'F');

  // Badge
  doc.setFillColor(79, 70, 229); // Indigo 600
  doc.roundedRect(margin + 6, currentY + 6, 44, 6, 2, 2, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7.5);
  doc.setTextColor(255, 255, 255);
  doc.text('SEO DIAGNOSTIC AUDIT', margin + 8, currentY + 10.2);

  // Report Title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(255, 255, 255);
  doc.text('Website SEO Health Audit Report', margin + 6, currentY + 22);

  // Target Domain
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10.5);
  doc.setTextColor(203, 213, 225); // Slate 300
  doc.text(`Target URL: ${report.url}`, margin + 6, currentY + 30);

  // Metadata Row
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184); // Slate 400
  const formattedDate = new Date(report.timestamp || Date.now()).toLocaleString('en-US', {
    dateStyle: 'medium',
    timeStyle: 'short',
  });
  doc.text(`Generated: ${formattedDate}   |   Report ID: ${report.id || 'SRT-' + Math.random().toString(36).substring(2, 9).toUpperCase()}`, margin + 6, currentY + 44);

  // Score Badge in top right corner of the banner
  const score = report.overallScore;
  let scoreBg = [16, 185, 129]; // Emerald 500
  if (score < 60) scoreBg = [225, 29, 72]; // Rose 600
  else if (score < 80) scoreBg = [245, 158, 11]; // Amber 500

  doc.setFillColor(scoreBg[0], scoreBg[1], scoreBg[2]);
  doc.roundedRect(pageWidth - margin - 38, currentY + 8, 32, 38, 3, 3, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(19);
  doc.setTextColor(255, 255, 255);
  doc.text(`${score}`, pageWidth - margin - 22, currentY + 24, { align: 'center' });

  doc.setFontSize(8);
  doc.text('/ 100', pageWidth - margin - 22, currentY + 30, { align: 'center' });

  doc.setFontSize(7);
  const ratingText = score >= 80 ? 'EXCELLENT' : score >= 60 ? 'FAIR' : 'NEEDS WORK';
  doc.text(ratingText, pageWidth - margin - 22, currentY + 39, { align: 'center' });

  currentY += 60;

  // Key Status Summary Cards (3 Columns)
  const colWidth = (contentWidth - 6) / 3;
  const criticalCount = report.statusSummary?.criticalCount || 0;
  const warningCount = report.statusSummary?.warningCount || 0;
  const passCount = report.statusSummary?.passCount || 0;

  // Card 1: Passed Checks
  doc.setFillColor(240, 253, 244); // Emerald 50
  doc.setDrawColor(187, 247, 208); // Emerald 200
  doc.roundedRect(margin, currentY, colWidth, 20, 2, 2, 'FD');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(5, 150, 105);
  doc.text(`${passCount}`, margin + 5, currentY + 9);
  doc.setFontSize(8);
  doc.setTextColor(6, 95, 70);
  doc.text('Passed Checks', margin + 5, currentY + 15);

  // Card 2: Warnings
  doc.setFillColor(254, 252, 232); // Amber 50
  doc.setDrawColor(254, 240, 138); // Amber 200
  doc.roundedRect(margin + colWidth + 3, currentY, colWidth, 20, 2, 2, 'FD');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(217, 119, 6);
  doc.text(`${warningCount}`, margin + colWidth + 8, currentY + 9);
  doc.setFontSize(8);
  doc.setTextColor(146, 64, 14);
  doc.text('Warnings / Notices', margin + colWidth + 8, currentY + 15);

  // Card 3: Critical Errors
  doc.setFillColor(255, 241, 242); // Rose 50
  doc.setDrawColor(254, 205, 211); // Rose 200
  doc.roundedRect(margin + (colWidth + 3) * 2, currentY, colWidth, 20, 2, 2, 'FD');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(225, 29, 72);
  doc.text(`${criticalCount}`, margin + (colWidth + 3) * 2 + 5, currentY + 9);
  doc.setFontSize(8);
  doc.setTextColor(159, 18, 57);
  doc.text('Critical SEO Errors', margin + (colWidth + 3) * 2 + 5, currentY + 15);

  currentY += 26;

  // Section Heading: Category Scores Breakdown
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(15, 23, 42);
  doc.text('Category Health Breakdown', margin, currentY + 2);
  currentY += 6;

  const categories = [
    { key: 'onpage', label: 'On-Page SEO', cat: report.categories?.onpage },
    { key: 'technical', label: 'Technical SEO', cat: report.categories?.technical },
    { key: 'performance', label: 'Page Speed & Core Web Vitals', cat: report.categories?.performance },
    { key: 'mobile', label: 'Mobile Usability & UX', cat: report.categories?.mobile },
    { key: 'security', label: 'Security & SSL', cat: report.categories?.security },
    { key: 'content', label: 'Content Quality & Headings', cat: report.categories?.content },
    { key: 'links', label: 'Links & Navigation', cat: report.categories?.links },
  ];

  categories.forEach((c) => {
    if (!c.cat) return;
    const catScore = c.cat.score || 0;
    const barWidth = 45;
    const filledWidth = Math.max(2, (catScore / 100) * barWidth);

    doc.setFillColor(248, 250, 252);
    doc.setDrawColor(226, 232, 240);
    doc.roundedRect(margin, currentY, contentWidth, 9, 1.5, 1.5, 'FD');

    // Label
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8.5);
    doc.setTextColor(30, 41, 59);
    doc.text(c.label, margin + 4, currentY + 6);

    // Checks summary
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(100, 116, 139);
    doc.text(
      `${c.cat.passCount || 0} passed, ${c.cat.warningCount || 0} warnings, ${c.cat.failCount || 0} issues`,
      margin + 75,
      currentY + 6
    );

    // Score Progress Bar
    const barX = pageWidth - margin - barWidth - 16;
    doc.setFillColor(226, 232, 240);
    doc.roundedRect(barX, currentY + 2.5, barWidth, 4, 1, 1, 'F');

    let cColor = [16, 185, 129];
    if (catScore < 60) cColor = [225, 29, 72];
    else if (catScore < 80) cColor = [245, 158, 11];

    doc.setFillColor(cColor[0], cColor[1], cColor[2]);
    doc.roundedRect(barX, currentY + 2.5, filledWidth, 4, 1, 1, 'F');

    // Score text
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8.5);
    doc.setTextColor(cColor[0], cColor[1], cColor[2]);
    doc.text(`${catScore}%`, pageWidth - margin - 4, currentY + 6, { align: 'right' });

    currentY += 10.5;
  });

  currentY += 4;

  // Metadata Snapshot Table
  checkPageBreak(40);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(15, 23, 42);
  doc.text('Essential SEO Metadata Snapshot', margin, currentY + 2);
  currentY += 6;

  const metadataItems = [
    { label: 'Title Tag', value: report.metadata?.title || '(None detected)', length: `${report.metadata?.titleLength || 0} chars` },
    { label: 'Meta Description', value: report.metadata?.description || '(None detected)', length: `${report.metadata?.descriptionLength || 0} chars` },
    { label: 'Canonical URL', value: report.metadata?.canonical || report.canonicalUrl || '(Not specified)', length: '' },
    { label: 'Robots Directive', value: report.metadata?.robots || 'index, follow (default)', length: '' },
  ];

  metadataItems.forEach((m) => {
    checkPageBreak(12);
    doc.setFillColor(255, 255, 255);
    doc.setDrawColor(226, 232, 240);
    doc.roundedRect(margin, currentY, contentWidth, 11, 1.5, 1.5, 'FD');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    doc.setTextColor(71, 85, 105);
    doc.text(m.label, margin + 4, currentY + 4.5);

    if (m.length) {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7);
      doc.setTextColor(148, 163, 184);
      doc.text(m.length, margin + 4, currentY + 8.5);
    }

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(15, 23, 42);
    const valText = doc.splitTextToSize(m.value, contentWidth - 45);
    doc.text(valText[0] || '', margin + 40, currentY + 6.5);

    currentY += 12.5;
  });

  // ================= DETAILED AUDIT FINDINGS BY CATEGORY =================
  categories.forEach((catObj) => {
    if (!catObj.cat || !catObj.cat.checks || catObj.cat.checks.length === 0) return;

    checkPageBreak(25);
    currentY += 4;

    // Category Header
    doc.setFillColor(241, 245, 249);
    doc.setDrawColor(203, 213, 225);
    doc.roundedRect(margin, currentY, contentWidth, 9, 1.5, 1.5, 'FD');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(15, 23, 42);
    doc.text(`${catObj.label} — Detailed Checks`, margin + 4, currentY + 6.2);

    doc.setFontSize(8);
    doc.setTextColor(79, 70, 229);
    doc.text(`Score: ${catObj.cat.score}/100`, pageWidth - margin - 4, currentY + 6.2, { align: 'right' });

    currentY += 11;

    // Individual checks in this category
    catObj.cat.checks.forEach((chk) => {
      checkPageBreak(16);

      let statusColor = [5, 150, 105]; // Green
      let statusBg = [240, 253, 244];
      let statusBadge = 'PASS';

      if (chk.status === 'FAIL') {
        statusColor = [225, 29, 72];
        statusBg = [255, 241, 242];
        statusBadge = 'FAIL';
      } else if (chk.status === 'WARNING') {
        statusColor = [217, 119, 6];
        statusBg = [254, 252, 232];
        statusBadge = 'WARN';
      }

      // Check item box
      doc.setFillColor(255, 255, 255);
      doc.setDrawColor(226, 232, 240);
      doc.roundedRect(margin, currentY, contentWidth, 14, 1.5, 1.5, 'FD');

      // Status pill
      doc.setFillColor(statusBg[0], statusBg[1], statusBg[2]);
      doc.setDrawColor(statusColor[0], statusColor[1], statusColor[2]);
      doc.roundedRect(margin + 3, currentY + 3, 14, 8, 1, 1, 'FD');

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(6.5);
      doc.setTextColor(statusColor[0], statusColor[1], statusColor[2]);
      doc.text(statusBadge, margin + 10, currentY + 8.5, { align: 'center' });

      // Check Name & Message
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8.5);
      doc.setTextColor(15, 23, 42);
      doc.text(chk.name, margin + 20, currentY + 5.5);

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7.5);
      doc.setTextColor(71, 85, 105);
      const msgLines = doc.splitTextToSize(chk.message || '', contentWidth - 24);
      doc.text(msgLines[0] || '', margin + 20, currentY + 10.5);

      currentY += 15.5;
    });
  });

  // ================= AI RECOMMENDATIONS / ACTION PLAN (IF PRESENT) =================
  if (report.aiRecommendations) {
    checkPageBreak(35);
    currentY += 6;

    // AI Section Header
    doc.setFillColor(238, 242, 255); // Indigo 50
    doc.setDrawColor(199, 210, 254);
    doc.roundedRect(margin, currentY, contentWidth, 10, 2, 2, 'FD');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10.5);
    doc.setTextColor(67, 56, 202);
    doc.text('Strategic SEO Optimization & Action Roadmap', margin + 4, currentY + 7);

    currentY += 13;

    // Summary Text
    if (report.aiRecommendations.summary) {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(51, 65, 85);
      const summaryLines = doc.splitTextToSize(report.aiRecommendations.summary, contentWidth);
      doc.text(summaryLines, margin, currentY);
      currentY += summaryLines.length * 4 + 4;
    }

    // Quick Wins
    if (report.aiRecommendations.quick_wins && report.aiRecommendations.quick_wins.length > 0) {
      checkPageBreak(25);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9);
      doc.setTextColor(15, 23, 42);
      doc.text('High-Impact Quick Wins:', margin, currentY);
      currentY += 4.5;

      report.aiRecommendations.quick_wins.slice(0, 4).forEach((win, idx) => {
        checkPageBreak(10);
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(8);
        doc.setTextColor(79, 70, 229);
        doc.text(`${idx + 1}.`, margin + 2, currentY + 3.5);

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(7.5);
        doc.setTextColor(30, 41, 59);
        const winLines = doc.splitTextToSize(win, contentWidth - 10);
        doc.text(winLines, margin + 8, currentY + 3.5);
        currentY += winLines.length * 3.8 + 2;
      });
    }
  }

  // Add Headers & Footers to all pages
  const totalPages = doc.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    drawHeader(p, totalPages);
    drawFooter();
  }

  // Clean filename
  const safeDomain = (report.domain || 'website').replace(/[^a-zA-Z0-9.-]/g, '_');
  const filename = `SEO_Audit_Report_${safeDomain}_${new Date().toISOString().split('T')[0]}.pdf`;

  // Trigger Save
  doc.save(filename);
}
